kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name | quote }}
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
  - name: udp3
    protocol: UDP
    port: 3333
    targetPort: 33333
  selector:
    name: {{ .Values.name | quote }}
